# Generated by Django 4.2 on 2023-04-27 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_employeedepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='DepartmentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmployeeApp.departments'),
        ),
    ]
