# Generated by Django 4.2 on 2023-04-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_employee_departmentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedepartment',
            old_name='Department_id',
            new_name='Departmentid',
        ),
        migrations.RenameField(
            model_name='employeedepartment',
            old_name='Employee_id',
            new_name='Employeeid',
        ),
    ]
