# Generated by Django 4.2 on 2023-05-01 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0006_teacher_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=10, null=True)),
                ('lastName', models.CharField(max_length=10, null=True)),
                ('hometown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birth', to='EmployeeApp.city')),
                ('living', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizen', to='EmployeeApp.city')),
                ('visitation', models.ManyToManyField(related_name='visitor', to='EmployeeApp.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.province'),
        ),
    ]
