# Generated by Django 4.2 on 2023-05-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0008_alter_city_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItEmployee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('dateOfBirth', models.DateField()),
            ],
        ),
    ]
